"use client";

import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import jsPDF from "jspdf";
import { Priority } from "../page";

interface Props {
  priorities: Priority[];
}

export default function ExportReport({ priorities }: Props) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Header
      doc.setFillColor(30, 64, 175); // brand-800
      doc.rect(0, 0, pageWidth, 40, "F");
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.text("Jan Awaaz - MP Briefing", 20, 25);
      
      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 20, 25, { align: "right" });

      // Title
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(16);
      doc.text("Top Constituency Priorities", 20, 55);

      let yPos = 70;

      priorities.slice(0, 5).forEach((p, index) => {
        if (yPos > 250) {
          doc.addPage();
          yPos = 30;
        }

        // Rank & Theme
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 64, 175);
        doc.text(`#${index + 1} ${p.theme_label}`, 20, yPos);
        
        // Gap Score Badge
        doc.setFillColor(p.gap_score > 0.7 ? 248 : p.gap_score > 0.5 ? 251 : 52, 
                         p.gap_score > 0.7 ? 113 : p.gap_score > 0.5 ? 146 : 211, 
                         p.gap_score > 0.7 ? 113 : p.gap_score > 0.5 ? 60 : 153);
        doc.rect(pageWidth - 45, yPos - 5, 25, 8, "F");
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(10);
        doc.text(`Score: ${(p.gap_score * 100).toFixed(0)}`, pageWidth - 42, yPos + 1);

        yPos += 8;

        // Details
        doc.setTextColor(100, 100, 100);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.text(`Ward: ${p.ward_name} | Citizen Submissions: ${p.submission_count}`, 20, yPos);
        
        yPos += 8;

        // AI Justification
        doc.setTextColor(50, 50, 50);
        doc.setFont("helvetica", "italic");
        const splitJustification = doc.splitTextToSize(`" ${p.justification} "`, pageWidth - 40);
        doc.text(splitJustification, 20, yPos);

        yPos += (splitJustification.length * 5) + 15;
      });

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by Jan Awaaz Decision Intelligence Platform", pageWidth / 2, 285, { align: "center" });

      doc.save("MP_Priority_Briefing.pdf");
    } catch (e) {
      console.error("Export failed", e);
      alert("Failed to generate PDF report.");
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={exporting || priorities.length === 0}
      className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold bg-surface-700 hover:bg-surface-600 border border-slate-700 text-white transition-colors disabled:opacity-50"
    >
      {exporting ? (
        <Loader2 className="w-4 h-4 animate-spin text-slate-400" />
      ) : (
        <Download className="w-4 h-4 text-brand-400" />
      )}
      <span className="hidden sm:inline">Export PDF</span>
    </button>
  );
}
